# Generated by Django 3.2.6 on 2021-08-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.TextField()),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('NNBC', models.TextField()),
                ('NR', models.TextField()),
                ('NP', models.TextField()),
                ('VV', models.TextField()),
                ('VA', models.TextField()),
                ('VX', models.TextField()),
                ('VCP', models.TextField()),
                ('VCN', models.TextField()),
                ('MM', models.TextField()),
                ('MAG', models.TextField()),
                ('MAJ', models.TextField()),
                ('IC', models.TextField()),
                ('JKS', models.TextField()),
                ('JKC', models.TextField()),
                ('JKG', models.TextField()),
                ('JKO', models.TextField()),
                ('JKB', models.TextField()),
                ('JKV', models.TextField()),
                ('JKQ', models.TextField()),
                ('JC', models.TextField()),
                ('JX', models.TextField()),
                ('EP', models.TextField()),
                ('EF', models.TextField()),
                ('EC', models.TextField()),
                ('ETN', models.TextField()),
                ('ETM', models.TextField()),
                ('XPN', models.TextField()),
                ('XSN', models.TextField()),
                ('XSV', models.TextField()),
                ('XSA', models.TextField()),
                ('XR', models.TextField()),
                ('SF', models.TextField()),
                ('SE', models.TextField()),
                ('SSO', models.TextField()),
                ('SSC', models.TextField()),
                ('SC', models.TextField()),
                ('SY', models.TextField()),
                ('SH', models.TextField()),
                ('SL', models.TextField()),
                ('SN', models.TextField()),
            ],
        ),
    ]
